### ISSUE TITLE
Is it possible to change the model into LLaMa3 and add more datasets?

### ISSUE THREAD

**Issue by Tizzzzy** [ChicagoHAI/active-example-selection#3]
Hi,
I see right now the main model that is using is gpt2, and dataset is AGNews. Is it possible to change the model to LLaMa3, and add more datasets such as SST-5, MRPC, QNLI, CMSQA(commonsense_qa) and SWAG?

**Comment by y0mingzhang** [comment]
We will not be adding new datasets or models. Please use issues only for _actual_ issues with our code.
